In [ ]:
%pip install polly-python

Collecting polly-python==3.1.0
  Downloading https://elucidatainc.github.io/PublicAssets/builds/polly-python/tests/testpolly/polly_python-3.1.0-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 3.1 MB/s eta 0:00:00a 0:00:01
Collecting requests==2.28.1
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: tqdm==4.65.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (4.65.0)
Requirement already satisfied: boto3<2.0,>=1.24.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.28.40)
Requirement already satisfied: cryptography<=38.0.0,>=37.0.1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (38.0.0)
Requirement already satisfied: python-jose==3.3.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (3.3.0)
Requirement already satisfied: pydantic==1.10.12 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.10.12)
Requirement already satisfied: numpy<=1.26.4 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.25.2)
Requirement already satisfied: mixpanel==4.10.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (4.10.0)
Requirement already satisfied: plotly>=5.0.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (5.18.0)
Requirement already satisfied: retrying==1.3.4 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.3.4)
Requirement already satisfied: botocore<2.0,>=1.27.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.31.40)
Requirement already satisfied: pytest>=6.2.5 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (7.4.3)
Collecting tabulate==0.9.0
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Requirement already satisfied: Deprecated>=1.2.12 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.2.14)
Requirement already satisfied: joblib>=1.2.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.3.2)
Collecting cmapPy<=4.0.1
  Downloading cmapPy-4.0.1-py2.py3-none-any.whl (150 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.2/150.2 kB 7.0 MB/s eta 0:00:00
Requirement already satisfied: rst2txt==1.1.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.1.0)
Requirement already satisfied: cloudpathlib>=0.15.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (0.16.0)
Requirement already satisfied: pandas<=2.2.2,>=1.3.5 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.5.3)
Requirement already satisfied: six>=1.9.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from mixpanel==4.10.0->polly-python==3.1.0) (1.16.0)
Requirement already satisfied: urllib3 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from mixpanel==4.10.0->polly-python==3.1.0) (1.26.16)
Requirement already satisfied: typing-extensions>=4.2.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pydantic==1.10.12->polly-python==3.1.0) (4.7.1)
Requirement already satisfied: pyasn1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from python-jose==3.3.0->polly-python==3.1.0) (0.5.0)
Requirement already satisfied: rsa in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from python-jose==3.3.0->polly-python==3.1.0) (4.7.2)
Requirement already satisfied: ecdsa!=0.15 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from python-jose==3.3.0->polly-python==3.1.0) (0.18.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from requests==2.28.1->polly-python==3.1.0) (2023.7.22)
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Requirement already satisfied: idna<4,>=2.5 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from requests==2.28.1->polly-python==3.1.0) (2.10)
Requirement already satisfied: docutils>=0.11 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from rst2txt==1.1.0->polly-python==3.1.0) (0.16)
Requirement already satisfied: pygments in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from rst2txt==1.1.0->polly-python==3.1.0) (2.16.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from boto3<2.0,>=1.24.0->polly-python==3.1.0) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from boto3<2.0,>=1.24.0->polly-python==3.1.0) (0.6.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from botocore<2.0,>=1.27.0->polly-python==3.1.0) (2.8.2)
Requirement already satisfied: h5py>=2.6.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from cmapPy<=4.0.1->polly-python==3.1.0) (3.10.0)
Requirement already satisfied: cffi>=1.12 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from cryptography<=38.0.0,>=37.0.1->polly-python==3.1.0) (1.15.1)
Requirement already satisfied: wrapt<2,>=1.10 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from Deprecated>=1.2.12->polly-python==3.1.0) (1.16.0)
Requirement already satisfied: pytz>=2020.1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pandas<=2.2.2,>=1.3.5->polly-python==3.1.0) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from plotly>=5.0.0->polly-python==3.1.0) (8.2.3)
Requirement already satisfied: packaging in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from plotly>=5.0.0->polly-python==3.1.0) (23.1)
Requirement already satisfied: tomli>=1.0.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pytest>=6.2.5->polly-python==3.1.0) (2.0.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pytest>=6.2.5->polly-python==3.1.0) (1.1.3)
Requirement already satisfied: iniconfig in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pytest>=6.2.5->polly-python==3.1.0) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pytest>=6.2.5->polly-python==3.1.0) (1.3.0)
Requirement already satisfied: pycparser in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from cffi>=1.12->cryptography<=38.0.0,>=37.0.1->polly-python==3.1.0) (2.21)
Installing collected packages: tabulate, charset-normalizer, requests, cmapPy, polly-python
  Attempting uninstall: tabulate
    Found existing installation: tabulate 0.8.10
    Uninstalling tabulate-0.8.10:
      Successfully uninstalled tabulate-0.8.10
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.2.0
    Uninstalling charset-normalizer-3.2.0:
      Successfully uninstalled charset-normalizer-3.2.0
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: polly-python
    Found existing installation: polly-python 1.0.0
    Uninstalling polly-python-1.0.0:
      Successfully uninstalled polly-python-1.0.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
polly-validator 0.0.2 requires requests==2.25.1, but you have requests 2.28.1 which is incompatible.
polly-validator 0.0.2 requires tabulate==0.8.10, but you have tabulate 0.9.0 which is incompatible.
Successfully installed charset-normalizer-2.1.1 cmapPy-4.0.1 polly-python-3.1.0 requests-2.28.1 tabulate-0.9.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# import

import os
import json
from polly.auth import Polly
from polly.workspaces import Workspaces
import pandas as pd

In [ ]:
# authentication 

AUTH_KEY = "auth key"
Polly.auth(AUTH_KEY, env="polly")

In [ ]:
# connect to workspace

workspaces = Workspaces()

In [ ]:
# get all workspaces

workspaces.fetch_my_workspaces()

,Workspace_id,Workspace_name,status,description,last_modified,tag_names,favourite,watch
0,16562,test_function_anshu,active,None,2024-09-30 11:13:02,[],False,False
1,16563,test_srishti,active,,2024-09-27 10:06:49,[],False,False
2,16556,new WS 21,active,,2024-09-25 08:27:05,[],False,False
3,16531,_PRD-870_Restored,active,,2024-09-25 07:04:58,[{'tag_name': 'PRD-870'}],False,True
4,15487,Test 2_Restored,active,,2024-09-19 12:35:14,[],False,False
...,...,...,...,...,...,...,...,...
188,14454,OA_484,archived,,2022-06-03 12:51:52,[],False,False
189,5803,TEST_NOTIFICATIONS,active,,2022-05-16 07:30:58,[],False,False
190,4060,Search_OGUI24_Restored_Restored,archived,,2022-05-09 12:01:40,[],False,False
191,4026,Copy URL workspace,active,,2022-03-30 07:07:09,[],False,True
192,4028,Notebooks,active,,2022-03-24 09:52:17,[],True,False

In [ ]:
# get content of a workspace with workspace id

query = workspaces.list_contents(workspace_id)
query

  file_name size last_modified
0   folder1    -             -

In [ ]:
#create new workspace with given name

workspaces.create_workspace("test_2024_04Nov")

INFO:root:Workspace Created !

{'name': 'test_2024_04Nov',
 'description': None,
 'project_property': {'type': 'workspaces', 'labels': ''},
 'created_time': '2024-11-04 09:48:30',
 'last_modified': '2024-11-04 09:48:30',
 'status': 1,
 'creator': 1647238511,
 'organisation': 1,
 'id': 16579,
 'tag_names': []}

In [ ]:
# copy content from one workspace to another

workspaces.create_copy({sorce workspace id}, "source path", {destination workspace id}, "destination path")

Workspace_copy started, You will be notified upon completion.
Copy Operation Successful!

In [ ]:
# download from a workspace

workspaces.download_from_workspaces({workspace id}, "workspace source path", "destination local path", copy_workspace_path=True)

INFO:root:Download successful to path=/import

In [ ]:
# upload from local to workspace

workspaces.upload_to_workspaces({workspace id}, "workspace destination path", "local source path")

INFO:root:Upload successful on workspace-id=16579.

In [ ]:
# sync workspace data from workspace to local

workspaces.sync_data({workspace id}, "polly://{workspace sorce path}","local destination path")

INFO:root:Sync successful on workspace-id=16563.