In [ ]:
%pip install polly-python

Collecting polly-python==3.1.0
  Downloading https://elucidatainc.github.io/PublicAssets/builds/polly-python/tests/testpolly/polly_python-3.1.0-py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 3.1 MB/s eta 0:00:00a 0:00:01
Collecting requests==2.28.1
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: tqdm==4.65.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (4.65.0)
Requirement already satisfied: boto3<2.0,>=1.24.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.28.40)
Requirement already satisfied: cryptography<=38.0.0,>=37.0.1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (38.0.0)
Requirement already satisfied: python-jose==3.3.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (3.3.0)
Requirement already satisfied: pydantic==1.10.12 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.10.12)
Requirement already satisfied: numpy<=1.26.4 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.25.2)
Requirement already satisfied: mixpanel==4.10.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (4.10.0)
Requirement already satisfied: plotly>=5.0.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (5.18.0)
Requirement already satisfied: retrying==1.3.4 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.3.4)
Requirement already satisfied: botocore<2.0,>=1.27.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.31.40)
Requirement already satisfied: pytest>=6.2.5 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (7.4.3)
Collecting tabulate==0.9.0
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Requirement already satisfied: Deprecated>=1.2.12 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.2.14)
Requirement already satisfied: joblib>=1.2.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.3.2)
Collecting cmapPy<=4.0.1
  Downloading cmapPy-4.0.1-py2.py3-none-any.whl (150 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.2/150.2 kB 7.0 MB/s eta 0:00:00
Requirement already satisfied: rst2txt==1.1.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.1.0)
Requirement already satisfied: cloudpathlib>=0.15.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (0.16.0)
Requirement already satisfied: pandas<=2.2.2,>=1.3.5 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from polly-python==3.1.0) (1.5.3)
Requirement already satisfied: six>=1.9.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from mixpanel==4.10.0->polly-python==3.1.0) (1.16.0)
Requirement already satisfied: urllib3 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from mixpanel==4.10.0->polly-python==3.1.0) (1.26.16)
Requirement already satisfied: typing-extensions>=4.2.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pydantic==1.10.12->polly-python==3.1.0) (4.7.1)
Requirement already satisfied: pyasn1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from python-jose==3.3.0->polly-python==3.1.0) (0.5.0)
Requirement already satisfied: rsa in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from python-jose==3.3.0->polly-python==3.1.0) (4.7.2)
Requirement already satisfied: ecdsa!=0.15 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from python-jose==3.3.0->polly-python==3.1.0) (0.18.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from requests==2.28.1->polly-python==3.1.0) (2023.7.22)
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Requirement already satisfied: idna<4,>=2.5 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from requests==2.28.1->polly-python==3.1.0) (2.10)
Requirement already satisfied: docutils>=0.11 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from rst2txt==1.1.0->polly-python==3.1.0) (0.16)
Requirement already satisfied: pygments in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from rst2txt==1.1.0->polly-python==3.1.0) (2.16.1)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from boto3<2.0,>=1.24.0->polly-python==3.1.0) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from boto3<2.0,>=1.24.0->polly-python==3.1.0) (0.6.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from botocore<2.0,>=1.27.0->polly-python==3.1.0) (2.8.2)
Requirement already satisfied: h5py>=2.6.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from cmapPy<=4.0.1->polly-python==3.1.0) (3.10.0)
Requirement already satisfied: cffi>=1.12 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from cryptography<=38.0.0,>=37.0.1->polly-python==3.1.0) (1.15.1)
Requirement already satisfied: wrapt<2,>=1.10 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from Deprecated>=1.2.12->polly-python==3.1.0) (1.16.0)
Requirement already satisfied: pytz>=2020.1 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pandas<=2.2.2,>=1.3.5->polly-python==3.1.0) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from plotly>=5.0.0->polly-python==3.1.0) (8.2.3)
Requirement already satisfied: packaging in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from plotly>=5.0.0->polly-python==3.1.0) (23.1)
Requirement already satisfied: tomli>=1.0.0 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pytest>=6.2.5->polly-python==3.1.0) (2.0.1)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pytest>=6.2.5->polly-python==3.1.0) (1.1.3)
Requirement already satisfied: iniconfig in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pytest>=6.2.5->polly-python==3.1.0) (2.0.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from pytest>=6.2.5->polly-python==3.1.0) (1.3.0)
Requirement already satisfied: pycparser in ./.environments/miniconda/envs/polly/lib/python3.10/site-packages (from cffi>=1.12->cryptography<=38.0.0,>=37.0.1->polly-python==3.1.0) (2.21)
Installing collected packages: tabulate, charset-normalizer, requests, cmapPy, polly-python
  Attempting uninstall: tabulate
    Found existing installation: tabulate 0.8.10
    Uninstalling tabulate-0.8.10:
      Successfully uninstalled tabulate-0.8.10
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.2.0
    Uninstalling charset-normalizer-3.2.0:
      Successfully uninstalled charset-normalizer-3.2.0
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
  Attempting uninstall: polly-python
    Found existing installation: polly-python 1.0.0
    Uninstalling polly-python-1.0.0:
      Successfully uninstalled polly-python-1.0.0

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
polly-validator 0.0.2 requires requests==2.25.1, but you have requests 2.28.1 which is incompatible.
polly-validator 0.0.2 requires tabulate==0.8.10, but you have tabulate 0.9.0 which is incompatible.
Successfully installed charset-normalizer-2.1.1 cmapPy-4.0.1 polly-python-3.1.0 requests-2.28.1 tabulate-0.9.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# import

import os
import json
from polly.omixatlas import OmixAtlas
from polly.jobs import jobs
import pandas as pd

In [ ]:
AUTH_KEY = "auth key"
Polly.auth(AUTH_KEY, env="polly")

In [ ]:
# connecting to omixatlas

omixatlas = OmixAtlas()
job = jobs()

In [ ]:
# create omixatlas

result = omixatlas.create(display_name = "test bulkrna OA sri", description = "this is for bulk rna seq diy ") 
print(result)

 OmixAtlas 1728297667220 Created
   Repository Id      Repository Name Category         Display Name  \
0  1728297667220  test_bulkrna_oa_sri  private  test bulkrna OA sri

                     Description
0  this is for bulk rna seq diy

In [ ]:
# updating a existing omixatlas

res = omixatlas.update(repo_key = "{repokey}", display_name = "test bulkrna OA sri", description = "this is the updated description of this omixatlas")
print(result)

In [ ]:
#getting basic details

omix_atlas_summary = pd.DataFrame.from_dict(omixatlas.omixatlas_summary('1722434200350'))['data']
omix_atlas_summary

cell_line_count                                                        1
cell_type_count                                                       11
data_source_count                                                      1
data_type_count                                                        1
dataset_count                                                          6
datatypes                            [{'raw counts transcriptomics': 6}]
disease_count                                                          8
drug_count                                                             1
indexes                                                               {}
linked_workspace_id                                                 None
normal_sample_count                                                  153
organism_count                                                         3
repo_id                                                    1722434200350
repo_name                                              bulk_rna_sri_test
sample_count                                                       574.0
sources                                                     [{'geo': 6}]
tissue_count                                                           4
v2_indexes             {'files': 'bulk_rna_sri_test_files', 'gct_col_...
Name: data, dtype: object

In [ ]:
# get all omixatlases

omixatlas.get_all_omixatlas()

{'data': [{'repo_name': 'bulk_rna_sri_test',
   'repo_id': '1722434200350',
   'indexes': {},
   'v2_indexes': {'files': 'bulk_rna_sri_test_files',
    'gct_col_metadata': 'bulk_rna_sri_test_gct_col_metadata'},
   'linked_workspace_id': None,
   'sources': [{'geo': 6}],
   'datatypes': [{'raw counts transcriptomics': 6}],
   'dataset_count': 6,
   'disease_count': 8,
   'tissue_count': 4,
   'organism_count': 3,
   'cell_line_count': 1,
   'cell_type_count': 11,
   'drug_count': 1,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 574.0,
   'normal_sample_count': 153},
  {'repo_id': '1724226646825',
   'repo_name': 'demo_srishti_omixatlas',
   'indexes': {},
   'v2_indexes': {},
   'data_management_version': 'v2',
   'sources': [],
   'datatypes': [],
   'dataset_count': 0,
   'disease_count': 0,
   'tissue_count': 0,
   'organism_count': 0,
   'cell_line_count': 0,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 0,
   'data_source_count': 0,
   'sample_count': 0,
   'normal_sample_count': 0},
  {'repo_id': '1669033066992',
   'repo_name': 'destination_atlas',
   'indexes': {'files': 'destination_atlas_files',
    'gct_col_metadata': 'destination_atlas_gct_col_metadata'},
   'v2_indexes': {'files': 'destination_atlas_files',
    'gct_col_metadata': 'destination_atlas_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 47}],
   'datatypes': [{'raw counts transcriptomics': 7}],
   'dataset_count': 47,
   'disease_count': 47,
   'tissue_count': 41,
   'organism_count': 4,
   'cell_line_count': 25,
   'cell_type_count': 0,
   'drug_count': 53,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 3383.0,
   'normal_sample_count': 0},
  {'repo_id': '1679482518578',
   'repo_name': 'details_page',
   'indexes': {'files': 'details_page_files',
    'gct_col_metadata': 'details_page_gct_col_metadata'},
   'v2_indexes': {'files': 'details_page_files',
    'gct_col_metadata': 'details_page_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'some source': 27},
    {'test': 1},
    {'testcrtnjrny': 1},
    {'this is a test': 1}],
   'datatypes': [{'raw counts transcriptomics': 27}, {'microarray': 3}],
   'dataset_count': 30,
   'disease_count': 42,
   'tissue_count': 28,
   'organism_count': 4,
   'cell_line_count': 15,
   'cell_type_count': 24,
   'drug_count': 12,
   'data_type_count': 2,
   'data_source_count': 4,
   'sample_count': 4263.0,
   'normal_sample_count': 2136},
  {'repo_id': '1685621126191',
   'repo_name': 'gdx_demo_atlas',
   'indexes': {'files': 'gdx_demo_atlas_files',
    'gct_col_metadata': 'gdx_demo_atlas_gct_col_metadata',
    'comparisons': 'gdx_demo_atlas_comparisons',
    'comparison_data': 'gdx_demo_atlas_comparison_data',
    'pathway_data': 'gdx_demo_atlas_pathway_data'},
   'v2_indexes': {'files': 'gdx_demo_atlas_files',
    'gct_col_metadata': 'gdx_demo_atlas_gct_col_metadata',
    'comparisons': 'gdx_demo_atlas_comparisons',
    'comparison_data': 'gdx_demo_atlas_comparison_data',
    'pathway_data': 'gdx_demo_atlas_pathway_data'},
   'data_management_version': 'v2',
   'sources': [{'geo': 37}],
   'datatypes': [{'raw counts transcriptomics': 29}, {'': 4}],
   'dataset_count': 37,
   'disease_count': 48,
   'tissue_count': 28,
   'organism_count': 6,
   'cell_line_count': 21,
   'cell_type_count': 18,
   'drug_count': 12,
   'data_type_count': 2,
   'data_source_count': 1,
   'sample_count': 947.0,
   'normal_sample_count': 267},
  {'repo_id': '1663151941472',
   'repo_name': 'c_oa',
   'indexes': {'files': 'c_oa_files'},
   'v2_indexes': {'files': 'c_oa_files'},
   'linked_workspace_id': 14918,
   'data_management_version': 'v2',
   'sources': [{'': 10}],
   'datatypes': [{'drug response': 10}],
   'dataset_count': 10,
   'disease_count': 3,
   'tissue_count': 1,
   'organism_count': 0,
   'cell_line_count': 5,
   'cell_type_count': 1,
   'drug_count': 1,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 10.0,
   'normal_sample_count': 0},
  {'repo_id': '1722598229271',
   'repo_name': 'bulk_rna_a_omixatlas',
   'indexes': {},
   'v2_indexes': {},
   'org_id': '1',
   'data_type': 'bulk_rna_seq',
   'data_management_version': 'v2',
   'sources': [],
   'datatypes': [],
   'dataset_count': 0,
   'disease_count': 0,
   'tissue_count': 0,
   'organism_count': 0,
   'cell_line_count': 0,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 0,
   'data_source_count': 0,
   'sample_count': 0,
   'normal_sample_count': 0},
  {'repo_id': '1659450268526',
   'repo_name': 'multiple_oa_2',
   'indexes': {'files': 'multiple_oa_2_files',
    'gct_col_metadata': 'multiple_oa_2_gct_col_metadata'},
   'v2_indexes': {'files': 'multiple_oa_2_files',
    'gct_col_metadata': 'multiple_oa_2_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'cbioportal': 225}, {'geo': 165}, {'depmap': 5}, {'tyra': 5}],
   'datatypes': [{'copy number variation': 191},
    {'transcriptomics': 165},
    {'mutation': 30},
    {'fusion': 4},
    {'gene dependency': 4},
    {'drug screens': 1}],
   'dataset_count': 400,
   'disease_count': 157,
   'tissue_count': 127,
   'organism_count': 7,
   'cell_line_count': 130,
   'cell_type_count': 62,
   'drug_count': 71,
   'data_type_count': 6,
   'data_source_count': 4,
   'sample_count': 276187.0,
   'normal_sample_count': 182293},
  {'repo_id': '1720168375094',
   'repo_name': 'single_cell_sri_test',
   'v2_indexes': {},
   'data_management_version': 'v2',
   'sources': [],
   'datatypes': [],
   'dataset_count': 0,
   'disease_count': 0,
   'tissue_count': 0,
   'organism_count': 0,
   'cell_line_count': 0,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 0,
   'data_source_count': 0,
   'sample_count': 0,
   'normal_sample_count': 0},
  {'repo_id': '1678794482481',
   'repo_name': 'csv_oa_test',
   'v2_indexes': {'files': 'csv_oa_test_files'},
   'linked_workspace_id': '15184',
   'data_management_version': 'v2',
   'sources': [{'src_1': 2},
    {'all': 1},
    {'test datastet': 1},
    {'test ondtst': 1}],
   'datatypes': [{'all': 3}, {'datatype_1': 2}],
   'dataset_count': 5,
   'disease_count': 4,
   'tissue_count': 4,
   'organism_count': 0,
   'cell_line_count': 0,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 2,
   'data_source_count': 4,
   'sample_count': 0.0,
   'normal_sample_count': 0},
  {'repo_id': '1663919116821',
   'repo_name': 'ai_in_drug_discovery_oa',
   'indexes': {'files': 'ai_in_drug_discovery_oa_files',
    'gct_col_metadata': 'ai_in_drug_discovery_oa_gct_col_metadata'},
   'v2_indexes': {'files': 'ai_in_drug_discovery_oa_files',
    'gct_col_metadata': 'ai_in_drug_discovery_oa_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 112}],
   'datatypes': [{'transcriptomics': 111}, {'microarray': 1}],
   'dataset_count': 112,
   'disease_count': 69,
   'tissue_count': 42,
   'organism_count': 6,
   'cell_line_count': 28,
   'cell_type_count': 60,
   'drug_count': 57,
   'data_type_count': 2,
   'data_source_count': 1,
   'sample_count': 3220.0,
   'normal_sample_count': 1579},
  {'repo_id': '1667375323145',
   'repo_name': 'bbio_omixatlas_only_h5seurat',
   'indexes': {'files': 'bbio_omixatlas_only_h5seurat_files'},
   'v2_indexes': {'files': 'bbio_omixatlas_only_h5seurat_files'},
   'data_management_version': 'v2',
   'sources': [{'branchbio': 4}],
   'datatypes': [{'single cell multiomics': 4}],
   'dataset_count': 4,
   'disease_count': 2,
   'tissue_count': 3,
   'organism_count': 1,
   'cell_line_count': 1,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 4.0,
   'normal_sample_count': 0},
  {'repo_id': '1689071945246',
   'repo_name': 'gdx_test_s',
   'v2_indexes': {'files': 'gdx_test_s_files',
    'gct_col_metadata': 'gdx_test_s_gct_col_metadata',
    'comparisons': 'gdx_test_s_comparisons',
    'comparison_data': 'gdx_test_s_comparison_data',
    'pathway_data': 'gdx_test_s_pathway_data'},
   'data_management_version': 'v2',
   'sources': [{'geo': 1}],
   'datatypes': [{'': 1}],
   'dataset_count': 1,
   'disease_count': 1,
   'tissue_count': 1,
   'organism_count': 1,
   'cell_line_count': 1,
   'cell_type_count': 2,
   'drug_count': 1,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 6.0,
   'normal_sample_count': 0},
  {'repo_id': '1673411159486',
   'repo_name': 'bulk_rnaseq_atlas',
   'indexes': {'files': 'bulk_rnaseq_atlas_files',
    'gct_col_metadata': 'bulk_rnaseq_atlas_gct_col_metadata'},
   'v2_indexes': {'files': 'bulk_rnaseq_atlas_files',
    'gct_col_metadata': 'bulk_rnaseq_atlas_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 4}, {'test2': 1}, {'testan': 1}],
   'datatypes': [{'raw counts transcriptomics': 5}, {'yo': 1}],
   'dataset_count': 6,
   'disease_count': 7,
   'tissue_count': 5,
   'organism_count': 3,
   'cell_line_count': 207,
   'cell_type_count': 7,
   'drug_count': 1,
   'data_type_count': 2,
   'data_source_count': 3,
   'sample_count': 237.0,
   'normal_sample_count': 88},
  {'repo_id': '31',
   'repo_name': 'lincs',
   'indexes': {'files': 'lincs_files',
    'gct_col_metadata': 'lincs_gct_col_metadata'},
   'v2_indexes': {'files': 'lincs_files',
    'gct_col_metadata': 'lincs_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo, lincs': 699}, {'geo': 95}, {'cbioportal': 2}],
   'datatypes': [{'transcriptomics': 794}, {'': 1}],
   'dataset_count': 796,
   'disease_count': 38,
   'tissue_count': 28,
   'organism_count': 2,
   'cell_line_count': 70,
   'cell_type_count': 4,
   'drug_count': 571,
   'data_type_count': 2,
   'data_source_count': 3,
   'sample_count': 198121.0,
   'normal_sample_count': 9062},
  {'repo_id': '1711002664882',
   'repo_name': 'archived_oa',
   'indexes': {},
   'v2_indexes': {},
   'data_management_version': 'v2',
   'sources': [],
   'datatypes': [],
   'dataset_count': 0,
   'disease_count': 0,
   'tissue_count': 0,
   'organism_count': 0,
   'cell_line_count': 0,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 0,
   'data_source_count': 0,
   'sample_count': 0,
   'normal_sample_count': 0},
  {'repo_id': '1670915426568',
   'repo_name': 'single_cell_destination',
   'indexes': {'files': 'single_cell_destination_files',
    'h5ad_col_metadata': 'single_cell_destination_h5ad_col_metadata'},
   'v2_indexes': {'files': 'single_cell_destination_files',
    'h5ad_col_metadata': 'single_cell_destination_h5ad_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 13}, {'tabula sapiens': 1}],
   'datatypes': [{'single cell': 14}],
   'dataset_count': 14,
   'disease_count': 15,
   'tissue_count': 14,
   'organism_count': 2,
   'cell_line_count': 3,
   'cell_type_count': 56,
   'drug_count': 11,
   'data_type_count': 1,
   'data_source_count': 2,
   'sample_count': 107.0,
   'normal_sample_count': 0},
  {'repo_id': '1654268055800',
   'repo_name': 'ingestion_test_1',
   'indexes': {'files': 'ingestion_test_1_files',
    'gct_col_metadata': 'ingestion_test_1_gct_col_metadata'},
   'v2_indexes': {'files': 'ingestion_test_1_files',
    'gct_col_metadata': 'ingestion_test_1_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 79},
    {'cbioportal': 13},
    {'ccle': 3},
    {'': 2},
    {'tcga': 1}],
   'datatypes': [{'transcriptomics': 64},
    {'': 26},
    {'copy_number_variation': 5},
    {'single_cell': 1}],
   'dataset_count': 98,
   'disease_count': 0,
   'tissue_count': 0,
   'organism_count': 0,
   'cell_line_count': 0,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 4,
   'data_source_count': 5,
   'sample_count': 0.0,
   'normal_sample_count': 386},
  {'repo_id': '1692767232097',
   'repo_name': 'prop_data_test',
   'v2_indexes': {},
   'data_management_version': 'v1',
   'sources': [],
   'datatypes': [],
   'dataset_count': 0,
   'disease_count': 0,
   'tissue_count': 0,
   'organism_count': 0,
   'cell_line_count': 0,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 0,
   'data_source_count': 0,
   'sample_count': 0,
   'normal_sample_count': 0},
  {'repo_id': '1694071639576',
   'repo_name': 'gdx_omixatlas',
   'v2_indexes': {'files': 'gdx_omixatlas_files',
    'gct_col_metadata': 'gdx_omixatlas_gct_col_metadata',
    'comparisons': 'gdx_omixatlas_comparisons',
    'comparison_data': 'gdx_omixatlas_comparison_data',
    'pathway_data': 'gdx_omixatlas_pathway_data'},
   'data_management_version': 'v1',
   'sources': [{'geo': 37}],
   'datatypes': [{'raw counts transcriptomics': 37}],
   'dataset_count': 37,
   'disease_count': 22,
   'tissue_count': 16,
   'organism_count': 0,
   'cell_line_count': 25,
   'cell_type_count': 12,
   'drug_count': 18,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 1136.0,
   'normal_sample_count': 364},
  {'repo_id': '1657777478388',
   'repo_name': 'ingestion_testing_oa',
   'indexes': {'files': 'ingestion_testing_oa_files',
    'gct_col_metadata': 'ingestion_testing_oa_gct_col_metadata'},
   'v2_indexes': {'files': 'ingestion_testing_oa_files',
    'gct_col_metadata': 'ingestion_testing_oa_gct_col_metadata'},
   'data_management_version': 'v1',
   'sources': [{'pride': 1}],
   'datatypes': [{'proteomics': 1}],
   'dataset_count': 1,
   'disease_count': 1,
   'tissue_count': 1,
   'organism_count': 1,
   'cell_line_count': 0,
   'cell_type_count': 1,
   'drug_count': 2,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 3.0,
   'normal_sample_count': 0},
  {'repo_id': '1677039559242',
   'repo_name': 'diy_poa',
   'indexes': {'files': 'diy_poa_files',
    'h5ad_col_metadata': 'diy_poa_h5ad_col_metadata'},
   'v2_indexes': {'files': 'diy_poa_files',
    'h5ad_col_metadata': 'diy_poa_h5ad_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 3}],
   'datatypes': [{'single cell': 3}],
   'dataset_count': 3,
   'disease_count': 4,
   'tissue_count': 3,
   'organism_count': 1,
   'cell_line_count': 1,
   'cell_type_count': 26,
   'drug_count': 1,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 8.0,
   'normal_sample_count': 0},
  {'repo_id': '1709709572426',
   'repo_name': 'vcf_demo2',
   'v2_indexes': {},
   'data_management_version': 'v2',
   'sources': [],
   'datatypes': [],
   'dataset_count': 0,
   'disease_count': 0,
   'tissue_count': 0,
   'organism_count': 0,
   'cell_line_count': 0,
   'cell_type_count': 0,
   'drug_count': 0,
   'data_type_count': 0,
   'data_source_count': 0,
   'sample_count': 0,
   'normal_sample_count': 0},
  {'repo_id': '1690534314003',
   'repo_name': 'hybrid_test_repo',
   'v2_indexes': {'files': 'hybrid_test_repo_files',
    'gct_col_metadata': 'hybrid_test_repo_gct_col_metadata',
    'h5ad_col_metadata': 'hybrid_test_repo_h5ad_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 2}, {'src_tst_1': 1}],
   'datatypes': [{'': 1},
    {'raw counts transcriptomics': 1},
    {'single cell': 1}],
   'dataset_count': 3,
   'disease_count': 6,
   'tissue_count': 2,
   'organism_count': 0,
   'cell_line_count': 1,
   'cell_type_count': 11,
   'drug_count': 1,
   'data_type_count': 3,
   'data_source_count': 2,
   'sample_count': 86.0,
   'normal_sample_count': 0},
  {'repo_id': '1659621145863',
   'repo_name': 'hmp_omixatlas',
   'indexes': {'files': 'hmp_omixatlas_files',
    'biom_col_metadata': 'hmp_omixatlas_biom_col_metadata',
    'biom_row_metadata': 'hmp_omixatlas_biom_row_metadata'},
   'v2_indexes': {'files': 'hmp_omixatlas_files',
    'biom_col_metadata': 'hmp_omixatlas_biom_col_metadata',
    'biom_row_metadata': 'hmp_omixatlas_biom_row_metadata'},
   'data_management_version': 'v2',
   'sources': [{'human microbiome project (hmp)': 32}, {'microbiome db': 1}],
   'datatypes': [{'metagenomics': 26},
    {'metatranscriptomics': 6},
    {'microbiome': 1}],
   'dataset_count': 33,
   'disease_count': 1,
   'tissue_count': 2,
   'organism_count': 1,
   'cell_line_count': 1,
   'cell_type_count': 1,
   'drug_count': 16,
   'data_type_count': 3,
   'data_source_count': 2,
   'sample_count': 1248.0,
   'normal_sample_count': 0},
  {'repo_id': '1666789252487',
   'repo_name': 'bbio_omixatlas',
   'indexes': {'files': 'bbio_omixatlas_files'},
   'v2_indexes': {'files': 'bbio_omixatlas_files'},
   'data_management_version': 'v2',
   'sources': [{'branchbio': 1}],
   'datatypes': [{'single cell multiomics': 1}],
   'dataset_count': 1,
   'disease_count': 1,
   'tissue_count': 1,
   'organism_count': 1,
   'cell_line_count': 1,
   'cell_type_count': 1,
   'drug_count': 0,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 1.0,
   'normal_sample_count': 0},
  {'repo_id': '17',
   'repo_name': 'sc_data_lake',
   'indexes': {'files': 'sc_data_lake_files',
    'h5ad_col_metadata': 'sc_data_lake_h5ad_col_metadata',
    'h5ad_row_metadata': 'sc_data_lake_h5ad_row_metadata'},
   'v2_indexes': {'files': 'sc_data_lake_files',
    'h5ad_col_metadata': 'sc_data_lake_h5ad_col_metadata',
    'h5ad_row_metadata': 'sc_data_lake_h5ad_row_metadata'},
   'data_management_version': 'v1',
   'sources': [{'geo': 105},
    {'expression atlas': 20},
    {'publication': 11},
    {'': 5},
    {'scp': 5},
    {'cziscience': 4},
    {'covid-19 cell atlas': 2},
    {'gene expression omnibus (geo)': 2},
    {'humancellatlas': 2}],
   'datatypes': [{'single cell': 132}, {'single cell1': 1}],
   'dataset_count': 156,
   'disease_count': 45,
   'tissue_count': 65,
   'organism_count': 3,
   'cell_line_count': 5,
   'cell_type_count': 163,
   'drug_count': 11,
   'data_type_count': 2,
   'data_source_count': 9,
   'sample_count': 1232147.0,
   'normal_sample_count': 0},
  {'repo_id': '1669085436194',
   'repo_name': 'source_atlas',
   'indexes': {'files': 'source_atlas_files',
    'gct_col_metadata': 'source_atlas_gct_col_metadata'},
   'v2_indexes': {'files': 'source_atlas_files',
    'gct_col_metadata': 'source_atlas_gct_col_metadata'},
   'data_type': 'bulk_rna_seq',
   'data_management_version': 'v1',
   'sources': [{'geo': 44}, {'': 1}, {'test': 1}],
   'datatypes': [{'raw counts transcriptomics': 44}, {'transcriptomics': 1}],
   'dataset_count': 46,
   'disease_count': 39,
   'tissue_count': 39,
   'organism_count': 8,
   'cell_line_count': 23,
   'cell_type_count': 26,
   'drug_count': 13,
   'data_type_count': 2,
   'data_source_count': 3,
   'sample_count': 3464.0,
   'normal_sample_count': 0},
  {'repo_id': '1674572370484',
   'repo_name': 'test_pipeline',
   'indexes': {'files': 'test_pipeline_files',
    'gct_col_metadata': 'test_pipeline_gct_col_metadata'},
   'v2_indexes': {'files': 'test_pipeline_files',
    'gct_col_metadata': 'test_pipeline_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 45}],
   'datatypes': [{'raw counts transcriptomics': 32}, {'transcriptomics': 13}],
   'dataset_count': 45,
   'disease_count': 34,
   'tissue_count': 18,
   'organism_count': 2,
   'cell_line_count': 9,
   'cell_type_count': 24,
   'drug_count': 9,
   'data_type_count': 2,
   'data_source_count': 1,
   'sample_count': 2922.0,
   'normal_sample_count': 2278},
  {'repo_id': '1673014297214',
   'repo_name': 'test_connector_pipeline',
   'indexes': {'files': 'test_connector_pipeline_files',
    'gct_col_metadata': 'test_connector_pipeline_gct_col_metadata'},
   'v2_indexes': {'files': 'test_connector_pipeline_files',
    'gct_col_metadata': 'test_connector_pipeline_gct_col_metadata'},
   'data_management_version': 'v2',
   'sources': [{'geo': 11}],
   'datatypes': [{'transcriptomics': 11}],
   'dataset_count': 11,
   'disease_count': 11,
   'tissue_count': 5,
   'organism_count': 2,
   'cell_line_count': 65,
   'cell_type_count': 7,
   'drug_count': 3,
   'data_type_count': 1,
   'data_source_count': 1,
   'sample_count': 141.0,
   'normal_sample_count': 29},

In [ ]:
# query metadata in omixatlases

query = "DESCRIBE bulk_rna_sri_test.samples"
results=omixatlas.query_metadata(query)
results.head()

Query execution succeeded (time taken: 2.53 seconds, data scanned: 0.000 MB)
Fetched 30 rows

             column_name    column_type
0                src_uri         string
1              sample_id         string
2  curated_gene_modified  array<string>
3      curated_cell_line         string
4    curated_cohort_name         string

In [19]:
query = "SHOW TABLES IN bulk_rna_sri_test"
results=omixatlas.query_metadata(query)
results.head()

Query execution succeeded (time taken: 3.20 seconds, data scanned: 0.000 MB)
Fetched 2 rows

                   table_name
0  bulk_rna_sri_test.datasets
1   bulk_rna_sri_test.samples